management:
  endpoints:
    web:
      exposure:
        include: '*'

## 下面的端点都是可用的：
# auditevents     显示当前应用程序的审计事件信息 [Yes]
# beans           显示一个应用中所有Spring Beans的完整列表 [Yes]
# conditions      显示配置类和自动配置类(configuration and auto-configuration classes)的状态及它们被应用或未被应用的原因	 [Yes]
# configprops     显示一个所有@ConfigurationProperties的集合列表 [Yes]
# env             显示来自Spring的 ConfigurableEnvironment的属性 [Yes]
# flyway          显示数据库迁移路径，如果有的话 [Yes]
# health          显示应用的健康信息（当使用一个未认证连接访问时显示一个简单的’status’，使用认证连接访问则显示全部信息详情） [Yes]
# info            显示任意的应用信息 [Yes]
# liquibase       展示任何Liquibase数据库迁移路径，如果有的话 [Yes]
# metrics         展示当前应用的metrics信息 [Yes]
# mappings        显示一个所有@RequestMapping路径的集合列表 [Yes]
# scheduledtasks  显示应用程序中的计划任务 [Yes]
# sessions        允许从Spring会话支持的会话存储中检索和删除(retrieval and deletion)用户会话。使用Spring Session对反应性Web应用程序的支持时不可用。 [Yes]
# shutdown        允许应用以优雅的方式关闭（默认情况下不启用） [Yes]
# threaddump      执行一个线程dump [Yes]

## 如果使用web应用(Spring MVC, Spring WebFlux, 或者 Jersey)，你还可以使用以下端点：
# heapdump        返回一个GZip压缩的hprof堆dump文件 [Yes]
# jolokia         通过HTTP暴露JMX beans（当Jolokia在类路径上时，WebFlux不可用） [Yes]
# logfile         返回日志文件内容（如果设置了logging.file或logging.path属性的话），支持使用HTTP Range头接收日志文件内容的部分信息	 [Yes]
# prometheus      以可以被Prometheus服务器抓取的格式显示metrics信息 [Yes]

## 默认情况下，除shutdown以外的所有端点均已启用, 要配置单个端点的启用，请使用management.endpoint.<id>.enabled属性
# 以下示例启用shutdown端点：
#management:
#  endpoint:
#    shutdown:
#      enabled: true

## 另外可以通过management.endpoints.enabled-by-default来修改全局端口默认配置,
# 以下示例启用info端点并禁用所有其他端点：
#management:
#  endpoints:
#    enabled-by-default: false
#  endpoint:
#    info:
#      enabled: true

## 由于端点可能包含敏感信息，因此应仔细考虑何时公开它们。下表显示了内置端点的默认曝光：
# ID              JMX   Web
# auditevents     Yes   No
# beans           Yes   No
# conditions      Yes   No
# configprops     Yes   No
# env             Yes   No
# flyway          Yes   No
# health          Yes   Yes
# heapdump        N/A   No
# httptrace       Yes   No
# info            Yes   Yes
# jolokia         Yes   No
# logfile         Yes   No
# logger          Yes   No
# liquibase       Yes   No
# metrics         Yes   No
# mappings        Yes   No
# prometheus      N/A   No
# scheduledtasks  Yes   No
# sessions        Yes   No
# shutdown        Yes   No
# threaddump      Yes   No

## 要更改公开哪些端点，请使用以下技术特定的include和exclude属性：
# [*]在YAML中有特殊的含义，所以如果你想包含（或排除）所有的端点，一定要加引号
#management:
#  endpoints:
#    jmx:
#      exposure:
#        exclude: '*'
#        include: '*'
#    web:
#      exposure:
#        exclude: '*'
#        include: info, health